//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterMiddle
    {
        public int Id { get; set; }
        public string FirstcolContext { get; set; }
        public string SecondcolHeader { get; set; }
        public string SecondcolContext { get; set; }
        public string ThirdcolHeader { get; set; }
        public string ThirdcolContextTop { get; set; }
        public string ThirdcolContextBottom { get; set; }
        public string FourthcolHeader { get; set; }
        public string FourthcolContextFirstspan { get; set; }
        public string FourthcolContextSecondspan { get; set; }
    }
}
