//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FooterBottom
    {
        public int Id { get; set; }
        public string ContextLeft { get; set; }
        public string ContextRightFirstSpan { get; set; }
        public string ContextRightSecondSpan { get; set; }
    }
}
